openapi: 3.0.0
info:
  title: Sample API
  version: "1.0"
  description: This is a sample API with a few errors.

paths:
  /users:
    get:
      summary: Get a list of users
      responses:
        '200':
          description: A JSON array of user objects
          content:
            application/json:
              schema:
                type: arr
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string

  /users/{userId}:
    get:
      summary: Get a user by ID
      parameters:
        - in: query
          name: userId
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: str

  /posts:
    post:
      summary: Create a new post
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
      responses:
        201:
          description: Post created successfully
        400:
          description: Invalid input
